mysite/Size/urls.py
from django.urls import  path
from Size import views
from django.urls.conf import include  
from django.conf import settings  
from django.conf.urls.static import static  



urlpatterns=[
    path('',views.show_size,name="show_size"),
    path('insert_size/',views.insert_size,name="insert_size"),
    path('size/edit_size/<int:id>/',views.edit_size,name="edit_size"),
    path('size/delete_size/<int:id>/',views.delete_size,name="delete_size")
]

mysite/categories/urls.py
from django.urls import  path
from categories import views
from django.urls.conf import include  
from django.conf import settings  
from django.conf.urls.static import static  



urlpatterns=[
    path('',views.show_cat,name="show_cat"),
    path('insert_cat/',views.insert_cat,name="insert_cat"),
    path('categories/edit_cat/<int:id>/',views.edit_cat,name="edit_cat"),
    path('categories/del_cat/<int:id>/',views.del_cat,name="del_cat")
]

mysite/colors/urls.py
from django.urls import  path
from colors import views
from django.urls.conf import include  
from django.conf import settings  
from django.conf.urls.static import static  



urlpatterns=[
    path('',views.show_colors,name="show_colors"),
    path('insert_colors/',views.insert_colors,name="insert_colors"),
    path('colors/edit_colors/<int:id>/',views.edit_colors,name="edit_colors"),
    path('colors/delete_colors/<int:id>/',views.delete_colors,name="delete_colors")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import  path
from polls import views
from django.urls.conf import include  
from django.conf import settings  
from django.conf.urls.static import static 

urlpatterns = [
    path('',include(('polls.urls','polls'),namespace='polls')),
    path('categories/',include(('categories.urls','categories'),namespace="categories")),
    path('colors/',include(('colors.urls','colors'),namespace="colors")),
    path('size/',include(('Size.urls','Size'),namespace="size")),
    path('sub_categories/',include(('sub_categories.urls','sub_categories'),namespace="sub_categories")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

mysite/polls/urls.py
from django.urls import  path
from polls import views
from django.urls.conf import include  
from django.conf import settings  
from django.conf.urls.static import static  

urlpatterns=[
    path('',views.showAdminPage,name="showadmin"),
    #show clothes
    path('show/',views.show,name="show"),
    #insert clothes
    path('insert/',views.insert,name="insert"),
    # path('Insert',views.Insertemp,name="Insertemp"),
    #eidt clothes information
    path('update/<int:id>/',views.update,name="update"),
    path('delete/<int:id>/',views.delete,name="delete")
    # path('Edit/<int:id>/',views.Editemp,name="Editemp"),
    # path('Update/<int:id>/',views.updateemp,name="updateemp"),
    # path('Delete/<int:id>/',views.Delemp,name="Delemp"),
]

mysite/sub_categories/urls.py
from django.urls import  path
from sub_categories import views
from django.urls.conf import include  
from django.conf import settings  
from django.conf.urls.static import static  



urlpatterns=[
    path('',views.show_sub_categories,name="show_sub_categories"),
    path('insert_sub_categories/',views.insert_sub_categories,name="insert_sub_categories"),
    path('sub_categories/edit_sub_categories/<int:id>/',views.edit_sub_categories,name="edit_sub_categories"),
    path('sub_categories/delete_sub_categories/<int:id>/',views.delete_sub_categories,name="delete_sub_categories")
]

mysite/polls/models.py
from tkinter import CASCADE
from django.db import models
from categories.models import Categories
from sub_categories.models import SUBCategories
from colors.models import Colors
from Size.models import Size
# Create your models here.
class Products(models.Model):
    categories = models.ForeignKey(Categories,on_delete=models.CASCADE)
    sub_categories = models.ForeignKey(SUBCategories,on_delete=models.CASCADE)
    color = models.ForeignKey(Colors,on_delete=models.CASCADE)
    size = models.ForeignKey(Size,on_delete=models.CASCADE)
    # image = models.ImageField(upload_to = 'media/',width_field=None,height_field=None,null=True)
    title = models.CharField(max_length=50)
    price = models.CharField(max_length=10)
    sku_number = models.CharField(max_length=10)
    product_details = models.CharField(max_length=300)
    quantity = models.IntegerField(default=0)
    isactive = models.BooleanField(default=True)
    

mysite/polls/views.py
from ast import If
from  django.shortcuts import render,redirect
from polls.models import Products
from django.contrib import messages
from polls.serializers import POLLSerializer 
from categories.models import Categories
from categories.serializers import CategoriesSerializer
from Size.models import Size
from Size.serializers import SizeSerializer
from colors.models import Colors
from colors.serializers import ColorsSerializer
from sub_categories.models import SUBCategories
from sub_categories.serializers import SUBCategoriesSerializer



def showAdminPage(request):
    showpage = Products.objects.all()
    serializer = POLLSerializer(showpage,many=True)
    return render(request,'polls/starter.html',{"data":serializer.data})

def show(request):
    showall = Products.objects.filter(isactive=True) 
    print("show all data:",showall)
    serializer = POLLSerializer(showall,many=True)  
    data = serializer.data
    
    for i in range(len(data)):
        product = Products.objects.filter(id=data[i]['id']).first()
        data[i]['categories'] = product.categories.__str__()
        data[i]['color'] = product.color.__str__()
        data[i]['size'] = product.size.__str__()
        data[i]['sub_categories'] = product.sub_categories.__str__()
   
    return render(request,'polls/product_list.html',{"data":data})


def insert(request):
    data = {}
    if request.method == "POST":
        print('POST',id)
        data['categories'] = request.POST.get('categories')
        data['sub_categories'] = request.POST.get('sub_categories')
        data['color'] = request.POST.get('color')
        data['size'] = request.POST.get('size')
        data['title'] = request.POST.get('title')
        data['price'] = request.POST.get('price')
        data['sku_number'] = request.POST.get('sku_number')
        data['product_details'] = request.POST.get('product_details')
        data['quantity'] = request.POST.get('quantity')

        form = POLLSerializer(data=data)
        print(form)
        if form.is_valid():
            print('form after valid:',form)
            print("error of form:",form.errors)
            form.save()
            
            messages.success(request, "Record Updated Successfully...!:)")
            return redirect("polls:show")
        else:
            print('form not valid')
            print(form.errors)
    if request.method == "GET":
        print('POST',id)
        category_dict = Categories.objects.filter(isactive=True)
        category = CategoriesSerializer(category_dict, many=True)
        sub_category_dict = SUBCategories.objects.filter(isactive=True)
        sub_category = SUBCategoriesSerializer(sub_category_dict,many=True)
        color_dict = Colors.objects.filter(isactive=True)
        color = ColorsSerializer(color_dict,many=True)
        size_dict = Size.objects.filter(isactive=True)
        size = SizeSerializer(size_dict,many=True)
        hm = {"context": category.data,"sub_context":sub_category.data,"color_context":color.data,"size_context":size.data}
        return render(request, "polls/product_insert.html", hm)
 



def update(request,id):
    if request.method == 'GET':
        print('GET',id)
        edit_clothes = Products.objects.filter(id=id).first()
        s= POLLSerializer(edit_clothes)
        return render(request,'polls/product_edit.html',{"Products":s.data})
    else:
        print('POST',id)
        update_clothes = {}
        
        d = Products.objects.filter(id=id).first()
        if d:
            update_clothes['Categories']=request.POST.get('Categories')
            update_clothes['sub_categories']=request.POST.get('sub_categories')
            update_clothes['lastname']=request.POST.get('lastname')
            update_clothes['Color']=request.POST.get('Color')
            update_clothes['Size']=request.POST.get('Size')
            update_clothes['image']=request.POST.get('image')
            update_clothes['title']=request.POST.get('title')
            update_clothes['sku_number']=request.POST.get('sku_number')
            update_clothes['prod_details']=request.POST.get('prod_details')
            update_clothes['quantity']=request.POST.get('quantity')
        # Updateemp = EmpModel.objects.get(id=id)
            #print(Updateemp)
            form = POLLSerializer(d,data=update_clothes)
            if form.is_valid():
                form.save()
                # print("hkjk",form.data)
                messages.success(request,'Record Updated Successfully...!:)')
                return redirect('polls:showemp')
            else:
                print(form.errors)




# def updateemp(request,id):
#     # Updateemp = {}
#     # if request.method=='POST':
#     #     data = EmpModel.objects.get(id=id)
#     #     if data:
#     #         Updateemp['firstname']=request.POST.get('firstname')
#     #         Updateemp['middlename']=request.POST.get('middlename')
#     #         Updateemp['lastname']=request.POST.get('lastname')
#     #         Updateemp['department']=request.POST.get('department')
#     #         Updateemp['designation']=request.POST.get('designation')
#     #         Updateemp['status']=request.POST.get('status')
#     #         Updateemp['salary']=request.POST.get('salary')
#     #         Updateemp['gender']=request.POST.get('gender')
#     #     # Updateemp = EmpModel.objects.get(id=id)
#     #         #print(Updateemp)
#     #         form = CRUDSerializer(data,data=Updateemp)
#     #         if form.is_valid():
#     #             form.save()
#     #             messages.success(request,'Record Updated Successfully...!:)')
#     #             return render(request,'Edit.html',{"EmpModel":Updateemp})
#     # return render(request,'Edit.html',Updateemp)


# def Delemp(request,id):
#     delemployee = Products.objects.get(id=id)
#     Delemp={}
#     #Delemp['isactive']=False
#     form = POLLSerializer(delemployee,data=Delemp)
#     if form.is_valid():
#         form.save()
#         messages.success(request,'Record Deleted Successfully...!:)')
#         return redirect('app1:showemp')
#     else:
#         print("sfsdrf",form.errors)
#         return redirect('app1:showemp')

def delete(request,id):
    deleteclothes = Products.objects.all(id=id)
    delclothes = {}
    delclothes['isactive']=False
    form = POLLSerializer(deleteclothes,data=delclothes)
    if form.is_valid():
        form.save()
        return redirect('polls:show')
    else:
        return redirect('polls:show')
    

mysite/templates/polls/edit_cat.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/4a3a231a50.js" crossorigin="anonymous"></script>
    <style>
        * {
            font-family: sans-serif;
            /* Change your font family */
        }

        
        table {
            border-collapse: collapse;
            table-layout: fixed;
            /* width: 100%; */
            /* padding-right: 1rem; */
           
        }

        th {
            border: 1px solid;
            border-bottom-color: #3c4fe0;
            border-left: 0px;
            border-right: 0px;
            border-top: 0px;
            color:gray;
            width: 200px;
        }


        th,
        td {
            text-align: left;
            padding: 2rem;
            white-space: nowrap;
            overflow: hidden;
            
            
        }
        tr{
            border-bottom: 1px solid;
            border-color: #D3D3D3;
        }
    </style>
</head>

<body>
    <center>
        <div class="jumbotron">
            <h1>EDIT CRUD creation</h1>
            <h1>Django webdevelopement</h1>
            <hr />
        </div>

        <form method="POST" >
            {% csrf_token %}
            <table> <!--content-table-->
                <thead>
                    <tr>
                        <td>Category ID</td>
                        <td><input type="text" name="id" value="{{Categories.id}}" readonly></td>
                    </tr>
                    <tr>
                        <td>Category Name</td>
                        <td><input type="text" name="category_name" value="{{Categories.category_name}}"></td>
                    </tr>
                    <tr>
                        <td>Category Description</td>
                        <td><input type="text" name="category_description" value="{{Categories.category_description}}"></td>
                    </tr>
                    
                    
                    <tr>
                        <td>
                            <!-- <input type="submit" value="update record"> -->
                            <a href="{% url 'categories:show_cat' %}">
                                <button type="submit" class="btn btn-success" value="update record">
                                    <i class="fa-solid fa-database"> Update Value</i>
                                </button>
                            </a>
                        </td>
                        <td>
                            {% if messages %}
                            {% for mess in messages %}
                            <b style="color:green;"> {{mess}} </b>
                            {% endfor %}
                            {% endif %}
                        </td>
                    </tr>
                </thead>
            </table>
            <button class="btn btn-success"><a href="{% url 'categories:show_cat' %}" style="color:red;">Home Page</a></button>

        </form>

    </center>
</body>

</html>

mysite/templates/polls/show_cat.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
    integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>
  <style>
    a {
      color: black;
    }

    .name {
      white-space: nowrap;
      width: 50px;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    body {
      font-family: "Lucida Console", "Courier New", monospace;
    }


    table {
      border-collapse: collapse;
      table-layout: fixed;
      /* width: 100%; */
      /* padding-right: 1rem; */

    }

    th {
      border: 1px solid;
      border-bottom-color: #3c4fe0;
      border-left: 0px;
      border-right: 0px;
      border-top: 0px;
      color: gray;
      width: 200px;
    }


    th,
    td {
      text-align: left;
      padding: 2rem;
      white-space: nowrap;
      overflow: hidden;


    }

    tr {
      border-bottom: 1px solid;
      border-color: #D3D3D3;
    }

    #create-btn {
      position: relative;
      left: 20rem;
    }

    .name {
      text-overflow: ellipsis;
      white-space: nowrap;
      overflow: hidden;
    }

  </style>
</head>

<body>
  <h1>Hello, world!</h1>

  <div class="container">
    <a href="{% url 'categories:insert_cat' %}">
      <button id="create-btn" class="btn btn-success btn-lg" ;>Create New Employee</button>
    </a>
    <table>
      <thead>
        <tr>
          <th>Category Name</th>
          <th>Category Description</th>
        </tr>
      </thead>

      {% for result in data %}
      <tbody>
        <tr>
          <td><b>{{result.category_name}}</b></td>
          <td><b>{{result.category_description}}</b></td>
          <td style="position: relative;left:50px;">
            <a href="categories/edit_cat/{{result.id}}">
              <button class="btn btn-primary">
                <i class="fa-solid fa-pen-to-square">EDIT</i>
              </button>
            </a>
          </td>
          <td>
            <a href="{% url 'categories:del_cat' result.id %}" onclick="return confirm('Are You Sure you want to delete?')">
              <button class="btn btn-danger">
                <i class="fa-solid fa-trash">DELETE</i>
              </button>
            </a>
          </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
    <a href="http://127.0.0.1:8000/">
      <button type="button" class="btn btn-primary">Go to Admin Home Page</button>
    </a>
    
  </div>
</body>

</html>

mysite/templates/polls/show_colors.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
    integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>
  <style>
    a {
      color: black;
    }

    .name {
      white-space: nowrap;
      width: 50px;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    body {
      font-family: "Lucida Console", "Courier New", monospace;
    }


    table {
      border-collapse: collapse;
      table-layout: fixed;
      /* width: 100%; */
      /* padding-right: 1rem; */

    }

    th {
      border: 1px solid;
      border-bottom-color: #3c4fe0;
      border-left: 0px;
      border-right: 0px;
      border-top: 0px;
      color: gray;
      width: 200px;
    }


    th,
    td {
      text-align: left;
      padding: 2rem;
      white-space: nowrap;
      overflow: hidden;


    }

    tr {
      border-bottom: 1px solid;
      border-color: #D3D3D3;
    }

    #create-btn {
      position: relative;
      left: 20rem;
    }

    .name {
      text-overflow: ellipsis;
      white-space: nowrap;
      overflow: hidden;
    }

  </style>
</head>

<body>
  <h1>Hello, world!</h1>

  <div class="container">
    <a href="{% url 'colors:insert_colors' %}">
      <button id="create-btn" class="btn btn-success btn-lg" ;>Create New Employee</button>
    </a>
    <table>
      <thead>
        <tr>
          <th>Color Name</th>
          <th>Color Description</th>
        </tr>
      </thead>

      {% for result in data %}
      <tbody>
        <tr>
          <td><b>{{result.color_name}}</b></td>
          <td><b>{{result.color_description}}</b></td>
          <td style="position: relative;left:50px;">
            <a href="colors/edit_colors/{{result.id}}">
              <button class="btn btn-primary">
                <i class="fa-solid fa-pen-to-square">EDIT</i>
              </button>
            </a>
          </td>
          <td>
            <a href="{% url 'colors:delete_colors' result.id %}" onclick="return confirm('Are You Sure you want to delete?')">
              <button class="btn btn-danger">
                <i class="fa-solid fa-trash">DELETE</i>
              </button>
            </a>
          </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
    <a href="http://127.0.0.1:8000/">
      <button type="button" class="btn btn-primary">Go to Admin Home Page</button>
    </a>
  </div>
</body>

</html>

mysite/templates/polls/show_sub_categories.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
    integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>
  <style>
    a {
      color: black;
    }

    .name {
      white-space: nowrap;
      width: 50px;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    body {
      font-family: "Lucida Console", "Courier New", monospace;
    }


    table {
      border-collapse: collapse;
      table-layout: fixed;
      /* width: 100%; */
      /* padding-right: 1rem; */

    }

    th {
      border: 1px solid;
      border-bottom-color: #3c4fe0;
      border-left: 0px;
      border-right: 0px;
      border-top: 0px;
      color: gray;
      width: 200px;
    }


    th,
    td {
      text-align: left;
      padding: 2rem;
      white-space: nowrap;
      overflow: hidden;


    }

    tr {
      border-bottom: 1px solid;
      border-color: #D3D3D3;
    }

    #create-btn {
      position: relative;
      left: 20rem;
    }

    .name {
      text-overflow: ellipsis;
      white-space: nowrap;
      overflow: hidden;
    }

  </style>
</head>

<body>
  <h1>Hello, world!</h1>

  <div class="container">
    <a href="{% url 'sub_categories:insert_sub_categories' %}">
      <button id="create-btn" class="btn btn-success btn-lg" ;>Create New Sub category</button>
    </a>
    <table>
      <thead>
        <tr>
          <th>Category Name</th>
          <th>Sub Category Name</th>
          <th>Sub Category Description</th>
        </tr>
      </thead>

      {% for result in results %}
      <tbody>
        <tr>
          <td><b>{{result.category_name}}</b></td>
          <td><b>{{result.sub_categories_name}}</b></td>
          <td><b>{{result.sub_categories_description}}</b></td>
          <td style="position: relative;left:50px;">
            <a href="sub_categories/edit_sub_categories/{{result.id}}">
              <button class="btn btn-primary">
                <i class="fa-solid fa-pen-to-square">EDIT</i>
              </button>
            </a>
          </td>
          <td>
            <a href="{% url 'sub_categories:delete_sub_categories' result.id %}" onclick="return confirm('Are You Sure you want to delete?')">
              <button class="btn btn-danger">
                <i class="fa-solid fa-trash">DELETE</i>
              </button>
            </a>
          </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
    <a href="http://127.0.0.1:8000/">
      <button type="button" class="btn btn-primary">Go to Admin Home Page</button>
    </a>
  </div>
</body>

</html>